# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 100.67.13.117:5000/mdesanti/node-http
  tag: 0.0.7
  pullPolicy: IfNotPresent
service:
  name: node-http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
nodeHttp:
  testVariabble: 'from repo values'
  dbUsername: localValues
  dbPassword: localValues
  dbHost: localValues
  dbPort: 5432
  dbName: localValues
